version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hospital_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
      POSTGRES_DB: hospital_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hospital_user -d hospital_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
